// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChm4C9GG-kbrQxNw_hT4fKB73qdsauGfg',
    appId: '1:821553068744:web:162b5bebbd48042b5643fd',
    messagingSenderId: '821553068744',
    projectId: 'kloti-last',
    authDomain: 'kloti-last.firebaseapp.com',
    storageBucket: 'kloti-last.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVpEJIdLa3k1jhIf_fJX13InpBeGqiMw',
    appId: '1:821553068744:android:4679f98623efd8bf5643fd',
    messagingSenderId: '821553068744',
    projectId: 'kloti-last',
    storageBucket: 'kloti-last.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkx_pMCf-OPTM1RRtphwEnNZ_64DPBlfA',
    appId: '1:821553068744:ios:86185e9877dc88925643fd',
    messagingSenderId: '821553068744',
    projectId: 'kloti-last',
    storageBucket: 'kloti-last.appspot.com',
    iosClientId: '821553068744-ld2t81etqilosthai96qu98udkef43mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterKloti',
  );
}
