// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJtswlLcJdAbj69oXXhWrll4_QHqnHZC0',
    appId: '1:182189255934:web:0ccf335e53221a7fd189af',
    messagingSenderId: '182189255934',
    projectId: 'kloti-login',
    authDomain: 'kloti-login.firebaseapp.com',
    storageBucket: 'kloti-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNR6Fmk_qjFIVnD9vrxryV0iVhGuYIqw',
    appId: '1:182189255934:android:bbb17f6620fbe740d189af',
    messagingSenderId: '182189255934',
    projectId: 'kloti-login',
    storageBucket: 'kloti-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEQcMNA8qQatJQYthArLFrSrnyrcZlzBs',
    appId: '1:182189255934:ios:c829e2e99203dbb6d189af',
    messagingSenderId: '182189255934',
    projectId: 'kloti-login',
    storageBucket: 'kloti-login.appspot.com',
    iosClientId: '182189255934-g018uj83vt43nl9iusrte8j69h11nlrt.apps.googleusercontent.com',
    iosBundleId: 'com.example.klotiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEQcMNA8qQatJQYthArLFrSrnyrcZlzBs',
    appId: '1:182189255934:ios:baa3544d1c93e72dd189af',
    messagingSenderId: '182189255934',
    projectId: 'kloti-login',
    storageBucket: 'kloti-login.appspot.com',
    iosClientId: '182189255934-hlgmfi73rfpal3utuvf2ricogfqtqfv8.apps.googleusercontent.com',
    iosBundleId: '.com.lacin.kloti',
  );
}
